/**
 * Run a single crawl cycle with the new BrowserCrawler
 * Run with: npm run crawl:once
 */

import { logger } from './utils/logger.js';
import { BrowserCrawler } from './services/browser-crawler.js';
import { JsonOutput } from './services/json-output.js';

async function crawlOnce() {
  logger.info('='.repeat(60));
  logger.info('FusionSolar Crawler - Single Run (Browser-based)');
  logger.info('='.repeat(60));
  logger.info('');

  const crawler = new BrowserCrawler();
  const jsonOutput = new JsonOutput();

  try {
    // Initialize output directories
    await jsonOutput.init();

    // Start browser
    logger.info('Step 1: Starting browser...');
    await crawler.start();

    // Login
    logger.info('');
    logger.info('Step 2: Logging in to FusionSolar...');
    await crawler.login();

    // Run crawl
    logger.info('');
    logger.info('Step 3: Crawling stations and devices...');
    const result = await crawler.crawl();

    // Save results to JSON
    logger.info('');
    logger.info('Step 4: Saving results to JSON...');
    const filepath = await jsonOutput.saveCrawlResult(result);

    // Also save individual station files
    for (const station of result.stations) {
      await jsonOutput.saveStation(station);
    }

    // Print summary
    logger.info('');
    logger.info('='.repeat(60));
    logger.info('CRAWL COMPLETE');
    logger.info('='.repeat(60));
    logger.info('');
    logger.info('Summary:');
    logger.info(`  - Duration: ${(result.duration / 1000).toFixed(1)}s`);
    logger.info(`  - Success: ${result.success}`);
    logger.info(`  - Stations: ${result.stations.length}`);
    logger.info(`  - Errors: ${result.errors.length}`);
    logger.info('');

    // Station details
    if (result.stations.length > 0) {
      logger.info('Stations:');
      for (const s of result.stations) {
        logger.info(`  ${s.station.stationName} (${s.station.stationDn})`);
        logger.info(`    - Current Power: ${s.realtimeKpi.currentPower} kW`);
        logger.info(`    - Yield Today: ${s.realtimeKpi.yieldToday} kWh`);
        logger.info(`    - Total Yield: ${s.realtimeKpi.totalYield} kWh`);
        logger.info(`    - Devices: ${s.devices.length}`);

        // Energy balance
        if (s.energyBalance.generatedByPV > 0 || s.energyBalance.fromGrid > 0) {
          logger.info(`    - Generated by PV: ${s.energyBalance.generatedByPV} kWh`);
          logger.info(`    - Fed to Grid: ${s.energyBalance.fedToGrid} kWh`);
          logger.info(`    - From Grid: ${s.energyBalance.fromGrid} kWh`);
        }

        // Environmental
        if (s.environmental.co2Avoided > 0) {
          logger.info(`    - CO2 Avoided: ${s.environmental.co2Avoided} tons`);
          logger.info(`    - Trees Planted: ${s.environmental.equivalentTreesPlanted}`);
        }
      }
    }

    // Errors
    if (result.errors.length > 0) {
      logger.info('');
      logger.warn('Errors:');
      for (const error of result.errors) {
        logger.warn(`  - [${error.endpoint}] ${error.message}`);
        if (error.stationDn) {
          logger.warn(`    Station: ${error.stationDn}`);
        }
      }
    }

    logger.info('');
    logger.info(`Output saved to: ${filepath}`);
    logger.info('View with: cat logs/crawl-latest.json | jq .');
    logger.info('');
  } catch (error) {
    logger.error('');
    logger.error('='.repeat(60));
    logger.error('CRAWL FAILED');
    logger.error('='.repeat(60));
    logger.error('Error:', error);
    process.exit(1);
  } finally {
    // Always close the browser
    await crawler.close();
  }
}

crawlOnce();
