/**
 * Test script for FusionSolar login
 * Run with: npm run test:login
 */

import { config } from './config/index.js';
import { logger } from './utils/logger.js';
import { FusionSolarAuthenticator } from './services/authenticator.js';
import { FusionSolarApiClient } from './services/api-client.js';

async function testLogin() {
  logger.info('='.repeat(60));
  logger.info('FusionSolar Login Test');
  logger.info('='.repeat(60));
  logger.info(`Login URL: ${config.fusionSolar.loginUrl}`);
  logger.info(`Username: ${config.fusionSolar.username}`);
  logger.info(`Headless: ${config.crawler.headless}`);
  logger.info('');

  const authenticator = new FusionSolarAuthenticator();
  const apiClient = new FusionSolarApiClient();

  try {
    // Step 1: Login
    logger.info('Step 1: Logging in to FusionSolar...');
    const session = await authenticator.login();

    logger.info(`Login successful! Got ${session.cookies.length} cookies`);
    logger.info('Cookies:');
    session.cookies.forEach((cookie) => {
      logger.info(`  - ${cookie.name}: ${cookie.value.substring(0, 20)}...`);
    });

    // Step 2: Set up API client
    logger.info('');
    logger.info('Step 2: Setting up API client...');
    apiClient.setCookies(session.cookies);

    // Step 3: Test session
    logger.info('');
    logger.info('Step 3: Testing session...');
    const isAlive = await apiClient.isSessionAlive();
    logger.info(`Session alive: ${isAlive}`);

    if (!isAlive) {
      throw new Error('Session is not alive');
    }

    // Step 4: Fetch stations
    logger.info('');
    logger.info('Step 4: Fetching station list...');
    const stations = await apiClient.getStationList();
    logger.info(`Found ${stations.length} stations:`);
    stations.forEach((station) => {
      logger.info(`  - ${station.stationName} (${station.stationDn})`);
    });

    // Step 5: Fetch data for first station
    if (stations.length > 0) {
      const firstStation = stations[0];
      logger.info('');
      logger.info(`Step 5: Fetching data for ${firstStation.stationName}...`);

      // Energy balance
      const energyBalance = await apiClient.getEnergyBalance(firstStation.stationDn);
      logger.info('Energy Balance:');
      logger.info(`  - Generated by PV: ${energyBalance.generatedByPV} kWh`);
      logger.info(`  - Fed to Grid: ${energyBalance.fedToGrid} kWh`);
      logger.info(`  - From Grid: ${energyBalance.fromGrid} kWh`);

      // Device list
      const devices = await apiClient.getDeviceList(firstStation.stationDn);
      logger.info(`Devices (${devices.length}):`);
      for (const device of devices) {
        logger.info(`  - ${device.deviceName} (${device.deviceType})`);

        // Get device data
        const deviceData = await apiClient.getDeviceRealtimeData(device.deviceDn);
        if (deviceData) {
          logger.info(`    Active Power: ${deviceData.activePower} kW`);
          logger.info(`    Daily Energy: ${deviceData.dailyEnergy} kWh`);
          logger.info(`    Status: ${deviceData.status}`);
        }
      }
    }

    logger.info('');
    logger.info('='.repeat(60));
    logger.info('LOGIN TEST SUCCESSFUL!');
    logger.info('='.repeat(60));
  } catch (error) {
    logger.error('');
    logger.error('='.repeat(60));
    logger.error('LOGIN TEST FAILED!');
    logger.error('='.repeat(60));
    logger.error('Error:', error);
    process.exit(1);
  }
}

testLogin();
